<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search_q</name>
   <tag></tag>
   <elementGuidId>36a8ebe5-2a29-43d1-b880-3b73336af11b</elementGuidId>
   <imagePath>Screenshots/Targets/Page_Become a client - Forrester/input_Search_q.png</imagePath>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#header-search-desktop</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value>Screenshots/Targets/Page_Become a client - Forrester/input_Search_q.png</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='header-search-desktop']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>IMAGE</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>14d872b5-8c81-41f2-8dbc-43decb09b14c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>header-search-desktop</value>
      <webElementGuid>9a9ac6b3-d864-4db1-ae62-d144cca71523</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>header-search__input js-header-search-input</value>
      <webElementGuid>591da356-b2e3-45ce-aae8-4427eba3726f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>eb36e7f0-6c5d-48e1-9165-5f54b2c1a187</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>q</value>
      <webElementGuid>1afe7837-0c70-4e08-95ca-f7354e313fae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header-search-desktop&quot;)</value>
      <webElementGuid>ddeef2ee-385f-4ef6-bea4-1edae4319522</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='header-search-desktop']</value>
      <webElementGuid>c717c974-0dc1-41ce-a576-2b00129e9556</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='site-nav']/div[2]/form/input</value>
      <webElementGuid>fc310eb5-235d-4ff7-a891-741314a3d7be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>ad8635aa-c2e9-4f08-8bb6-dbc824d94443</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'header-search-desktop' and @type = 'search' and @name = 'q']</value>
      <webElementGuid>a6e6b1dc-04ea-44b4-a6a9-d590ef889368</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
