<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search_q</name>
   <tag></tag>
   <elementGuidId>bd33ee9a-c4da-4d40-a896-fcf3f42b441a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#header-search-desktop</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='header-search-desktop']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0cc57846-8582-4491-ae51-fc380160ae89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>header-search-desktop</value>
      <webElementGuid>7adbc872-f36d-49cd-b85c-cd9bc418fc0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>header-search__input js-header-search-input</value>
      <webElementGuid>ee394551-584b-45af-97bb-738ec984d415</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>a7a07720-dda7-4017-9633-57a8e705edeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>q</value>
      <webElementGuid>cdcc0555-29d1-4d59-acca-cd9f297d34da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header-search-desktop&quot;)</value>
      <webElementGuid>d6e6a6b7-8270-4cd7-b5a8-53a733880313</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='header-search-desktop']</value>
      <webElementGuid>4d4e816b-f979-4306-8ad5-f2e78a87b5d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='site-nav']/div[2]/form/input</value>
      <webElementGuid>6fb29f82-f8b0-4686-9189-6f4731c270c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>06b7d879-96b7-435d-892a-c601faaa8e9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'header-search-desktop' and @type = 'search' and @name = 'q']</value>
      <webElementGuid>d8717a4c-56e0-4595-87c3-b72f9a077893</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
