<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ham</name>
   <tag></tag>
   <elementGuidId>a6de57a0-90bb-4a72-bbd2-574321195038</elementGuidId>
   <imagePath>C:\Users\duc.phan\Desktop\ham.png</imagePath>
   <selectorCollection>
      <entry>
         <key>IMAGE</key>
         <value>C:\Users\duc.phan\Desktop\ham.png</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>IMAGE</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
