<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Log in_search-input-9</name>
   <tag></tag>
   <elementGuidId>f6a992ea-8d78-446c-a13f-e67c53c1e86f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#search-input-9</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='search-input-9']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fbf98f37-6fcd-4804-88bc-bf90fc7b4c9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>search-input-9</value>
      <webElementGuid>2a189bba-372f-4f75-ad2e-c768fed759c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0882370e-f858-4ad3-a21f-eeec293c3883</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>3484b9ec-d858-48b8-9ea9-12a66a3fbafa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search for reports, insights, models, tools, and other research...</value>
      <webElementGuid>7aa87fbc-caca-4a14-81fb-934ccd5f0e2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>dff390c0-5dfe-48ee-b699-7d7e37bb6e19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>search-list-10</value>
      <webElementGuid>6059013e-0551-4107-822e-7013954b21bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-owns</name>
      <type>Main</type>
      <value>search-list-10</value>
      <webElementGuid>ada8394a-bb1c-4ba9-9ad8-964eb1caae55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>ad1624e8-1f14-48f2-b702-d45e2fa09815</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>searchbox</value>
      <webElementGuid>f1dbe3c0-a312-4c92-9470-bcdc999c66de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Start typing for suggestions, use arrow keys to navigate.</value>
      <webElementGuid>fda91c41-fcb7-4d63-95ec-554b880c8d90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input__field focus-visible</value>
      <webElementGuid>f68c8719-6298-481a-bb4e-a2e0babd7c6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search-input-9&quot;)</value>
      <webElementGuid>f6a51cbe-3e21-4277-8e76-3333fff6999a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='search-input-9']</value>
      <webElementGuid>3c50fe17-1366-4dd8-9e5b-5204e52d4aa3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/main/div/div/div/section/div/div/section/div/div/div/input</value>
      <webElementGuid>7262c389-5698-4232-92a7-a8877793df05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/input</value>
      <webElementGuid>eda3f854-3b95-46fd-bf79-8e0824e7ab87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'search-input-9' and @type = 'text' and @placeholder = 'Search for reports, insights, models, tools, and other research...']</value>
      <webElementGuid>da5b8b05-6bab-4360-8ea2-267531f26367</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
