<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Reports</name>
   <tag></tag>
   <elementGuidId>f51ae2f2-5855-4d72-b455-f10074805602</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__layout']/div/main/div/div/div[2]/div/section/div[2]/button[2]/div/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>db34d0bd-cf97-489b-b8db-aa7b40f77c05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tab__label</value>
      <webElementGuid>95f942d5-887c-4b61-8692-a8fc3a201fe4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
        Reports
        </value>
      <webElementGuid>601f46d0-483f-4adc-8a31-876396fe86d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[@class=&quot;layout-new-default layout-new-default--no-access-flags&quot;]/main[1]/div[@class=&quot;all-search&quot;]/div[@class=&quot;all-search__content&quot;]/div[@class=&quot;all-search__tab-container&quot;]/div[@class=&quot;fe-template-fluid&quot;]/section[@class=&quot;tab-bar tab-bar--secondary-horizontal tab-bar--light tab-bar--left tab-bar--large&quot;]/div[@class=&quot;tab-bar__inner&quot;]/button[@class=&quot;tab-bar__button tab tab--secondary-horizontal tab--light tab--large&quot;]/div[@class=&quot;tab__content&quot;]/div[@class=&quot;tab__label-wrapper&quot;]/span[@class=&quot;tab__label&quot;]</value>
      <webElementGuid>47c8333d-a91c-4a15-9272-f9d53c6e0e2f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/main/div/div/div[2]/div/section/div[2]/button[2]/div/div/span</value>
      <webElementGuid>c22e51e1-7dc6-47b6-a6b8-5cc837eccad7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reports'])[1]/following::span[1]</value>
      <webElementGuid>9d070698-1325-4381-badf-2cb057128b0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All'])[2]/following::span[1]</value>
      <webElementGuid>d9a6dc6d-075c-4ef9-822e-42684efafe0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tools'])[1]/preceding::span[1]</value>
      <webElementGuid>4a8984d7-f79d-47eb-8b0b-a2bcf06c83f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tools'])[2]/preceding::span[1]</value>
      <webElementGuid>2f07cd90-aab9-41f7-9354-859c97340f8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]/div/div/span</value>
      <webElementGuid>8b66595e-b2fb-4551-9071-f5b178323851</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '
        Reports
        ' or . = '
        Reports
        ')]</value>
      <webElementGuid>971cb6cc-5c7f-4992-891f-6ace090324b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
